In [3]:
import numpy as np

A = [[0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
	[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
	[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]]




In [4]:
#1. Does the adjacency matrix represent a simple graph?
simple = np.max(A) == 1
print(simple)

True


In [5]:
#2. Can the adjacency matrix potentially represent an undirected graph?
#Undirected graph has symmetric adjacency matrix
#TODO: find a more efficient check for large, sparse matrix
A_T = np.transpose(A)
print(np.all(A-A_T) == 0)

True


In [9]:
#3. Is the graph connected?
#IE is there a path between every component
#10 nodes so max path length = 9
#TODO: consider a more efficient method for sparse matrices
print(A)

B = np.linalg.matrix_power(A,9)
#print(B)
print(np.all(B) > 0)


[[0, 1, 0, 1, 0, 1, 0, 0, 0, 0], [1, 0, 1, 1, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1, 0], [0, 1, 0, 0, 0, 0, 0, 0, 1, 1], [1, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 1, 0, 0, 0, 0, 1], [0, 0, 0, 0, 1, 0, 1, 0, 1, 0]]
[[4600 5244 1558 5939 3578 3489  814 1978 4001 2679]
 [5244 4940 2070 7340 4609 3395  955 1837 3889 2973]
 [1558 2070  448 1837 1097 1337  292  791 1584  955]
 [5939 7340 1837 7162 4367 4810 1123 2832 5694 3483]
 [3578 4609 1097 4367 2760 2948  744 1739 3643 2336]
 [3489 3395 1337 4810 2948 2334  601 1270 2613 1937]
 [ 814  955  292 1123  744  601  182  337  776  605]
 [1978 1837  791 2832 1739 1270  337  670 1407 1123]
 [4001 3889 1584 5694 3643 2613  776 1407 3102 2472]
 [2679 2973  955 3483 2336 1937  605 1123 2472 1702]]
True


In [10]:
#4. What is the minimum l such that A^l  contains no entry equal to 0 If such an l does not exist, then enter -1
#TODO: this will be inefficient for large matrices
for _ in range(2,9):
    if np.all(np.linalg.matrix_power(A,_) > 0):
        print (f"minimum l is {_}")
        break

minimum l is 4


In [11]:
#5. How many connected components does the graph have?
print("1 since all nodes can be reached within 4 steps")

1 since all nodes can be reached within 4 steps


In [12]:
#6. What is the maximum degree of a node in the graph?
for row in A:
    print(np.sum(row))

3
4
1
5
3
2
1
1
3
3


In [16]:
#7 How many walks of length 5 are there from node 0 (represented by first row/column) to itself?
print(np.linalg.matrix_power(A,5)[0,0])

46


In [14]:
#8. Is the following statement True or False? “For an undirected graph, that is not weighted or a multigraph, the diagonal entries of A^2 are equal to the degree of the nodes."
print("True since for undirected graph adjacency matrix is symmetrical so Aii = dot product of row i = sum of 1s in the row")

True since for undirected graph adjacency matrix is symmetrical so Aii = dot product of row i = sum of 1s in the row
